###
# This workflow is used for daily build
# Triggers:
#   1. Manual trigger
# Jobs:
#   1. Build Web Artifact (include front resource and only x86_64 platform for now)
###

name: Daily build
run-name: Daily build triggered by ${{ github.actor }} 🎉

on:
  workflow_dispatch:
    inputs:
      rpm_release:
        description: "Rpm release number"
        required: false
        default: ''
        type: string

jobs:
  build-jar:
    name: Build Web Artifact (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven
      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.20.0"
      - name: Build front static resources
        run: |
          echo "Current directory: "`pwd`
          echo "Start build front static resources"
          pushd frontend
          echo "Run npm install"
          npm install --legacy-peer-deps
          echo "Run npm build"
          npm run build
          echo "Build front static resources success"
          echo "Start copy resources files"
          popd
          static_resources_path="server/src/main/resources/static"
          if [ ! -d "${static_resources_path}" ]; then
            echo "mkdir -p ${static_resources_path}"
            mkdir -p "${static_resources_path}"
          fi
          rm --force --recursive --verbose ${static_resources_path}/*
          cp --force --recursive --verbose frontend/dist/* ${static_resources_path}
          echo "Copy resources files success"
      - name: Build jar & rpm (x86_64)
        run: |
          echo "Start build jar"
          mvn help:system
          mvn -q clean install -Dmaven.test.skip=true
          echo "Jar path: $(find server/target -name '*.jar')"
          echo "Start build rpm"
          rpm_release_number=$(date +%Y%m%d)
          if [[ -n "${{ inputs.rpm_release }}" ]]; then rpm_release_number="${{ inputs.rpm_release }}"; fi
          export RELEASE=${rpm_release_number}
          mkdir -p rpmbuild/BUILD rpmbuild/BUILDROOT rpmbuild/RPMS rpmbuild/SRPMS rpmbuild/SOURCES rpmbuild/SOURCES
          rpmbuild --define "_topdir $(pwd)/rpmbuild" --define "_workspace $(pwd)" -bb --quiet "$(pwd)"/rpm/ocp-express.spec
          echo "RPM path: $(find $(pwd)/rpmbuild/RPMS -name '*.rpm')"
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: ocp-express-server-jar
          path: server/target/*.jar
      - name: Upload rpm (x86_64)
        uses: actions/upload-artifact@v3
        with:
          name: ocp-express-rpm
          path: rpmbuild/RPMS/x86_64/ocp-express-*.rpm
